spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userjob
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    database: postgresql
    hibernate.ddl-auto: validate

  liquibase:
    changeLog: classpath:/liquibase/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: false

server:
  port: 8080
